### ISSUE TITLE
URI as Metric causes error in UI

### ISSUE THREAD

**Issue by jdarling** [bosun-monitor/bosun#1457] opened 2015-11-12 17:37 UTC
If you record a new metric where the Metric Name contains /'s it will blow up the UI due to the API call that it makes.  These should probably be escaped by default or the /api/tagk/ handler should catch and use the entire path after it instead of just the first segment.

**Comment by captncraig** [comment] 2015-11-19 08:15
Duplicate of #1305

**Closed by captncraig** 2015-11-19 08:15 UTC
Labels: bug
