### ISSUE TITLE
Error in search.go when using latest alpha build

### ISSUE THREAD

**Issue by cedw93** [bosun-monitor/bosun#1606] opened 2016-02-19 01:53 UTC
I upgraded to the latest master today and all seemed to be running smoothly until the following error occurred and 'spammed' our alert endpoints with 'ghost' alerts.

To clarify a ghost alert in this context is one that doesn't have a name associated with it (see below).

For reference I am running on an AWS EC2 instance running Amazon Linux using `go version go1.5.1 linux/amd64` (Do I need 1.6?)

An example config for an alert is my system as is follows:

```
tsdbHost = localhost:4242
stateFile = bosun.state
logstashElasticHosts = http://<someip>:9200

notification level1_alert {
        post = http://localhost:8090/notify-endpoints
        body = {"subject": {{.|json}},"html":"This is a level 1 alert"}
        contentType = application/json
        print = true
        next = level1_alert
        timeout = 5m
}

template sbx_rs {
    subject = {{.Last.Status}}: {{.Alert.Name}} on {{.Group.host}}
    body = `<p>Name: {{.Alert.Name}}
    <p>Tags:
    <table>
        {{range $k, $v := .Group}}
            <tr><td>{{$k}}</td><td>{{$v}}</td></tr>
        {{end}}
    </table>`
}

alert primary.count{
    template = sbx_rs
    critNotification = level1_alert
    $min = min(q("sum:primary.count{host=*}", "1h", ""))
    crit = $min < 1
}
```

When the system is functioning normally the endpoint would recieve JSON that contents `subject: critical: primary.count`.

However, recently on the latest master out of nowhere I've started getting alerts where the subject is a blank string, and there is no alert in the bosun dashboard either (hense ghost alert).

I found the following error in the bosun log:

```
01:20:04 error: search.go:70: cannot convert string to float64
```

In addition to this, when on the rule editor page if iI tested any alert I got an error `'invalid command param' but the config does `validate`, and about 10hours or so earlier the alerts were in fact testable.

I've reverted back to my install of 0.3 and it works as expected using the same config as above.

**Comment by captncraig** [comment] 2016-02-22 17:08
what is the original source of the data points? It is getting hung up on finding json strings in the datapoints, which I have not observed in any system so far. Everything I have seen sends Value as a numeric field. I can certainly parse the string as a number, but would like to have insight into what is sending this.

**Comment by kylebrandt** [comment] 2016-02-22 17:12
In our opentsdb package, the value of a datapoint is an interface{}:

```
// DataPoint is a data point for the /api/put route:
// http://opentsdb.net/docs/build/html/api_http/put.html#example-single-data-point-put.
type DataPoint struct {
	Metric    string      `json:"metric"`
	Timestamp int64       `json:"timestamp"`
	Value     interface{} `json:"value"`
	Tags      TagSet      `json:"tags"`
}
```

So strings are accepted, maybe they don't get converted to a float before going into redis?

**Comment by cedw93** [comment] 2016-02-22 17:31
Im sure which metric was causing the error but im using exactly the same data with version 0.3 and it all works fine. All the data I send is a float representation Im not sending any string values.

**Comment by captncraig** [comment] 2016-02-22 17:57
Yes, there have been significant changes to that system since 0.3. The error that is printing is a result of trying to store the last value of each metric as we see it. It was likely not doing that level of inspection in that old of a version.

Again, what is the source of the metrics? Can you share some of the raw json it is sending? The only way I can see to get that particular message is to send a json string, likely something like `"value":"42"`. 

We can, as I said, handle that, but I would like to more fully understand the end to end scenario here.

**Comment by cedw93** [comment] 2016-02-22 18:03
Makes sense I am sending it through as string representation, for example:

```
{"metric":"some-metric","timestamp":1456162802,"value":"0","tags":{"host":"test.host"}}
```

The data collector/dispatcher is quite lightweight would prefer not having to have to check typings/cast value so we generally use strings. Data gets sent to more than one endpoint some of which only accept string values so we decided its not worth writing several different versions of the method to handle this. 

Understandable things have changed, seems to be sending a string that caused the error then.

**Comment by captncraig** [comment] 2016-02-22 18:04
the good news is, that error is not stopping anything serious from working. There have been several unrelated empty email bugs that should be resolved by now. If you can build from master I would be curious to see if you can reproduce the same things.

**Comment by cedw93** [comment] 2016-02-22 18:07
Will do it tomorrow gotta shoot out now.

The weird thing is I was running the alpha build for about 10hours sending the above data every 20mins or so and now empty emails occurred, then suddenly it started happening. Ill give it another go for sure Ill report back if I find anything.

**Comment by kylebrandt** [comment] 2016-03-15 17:21
@cedw93 Were you able to reproduce in the newer version?

**Closed** 2016-06-13 17:30 UTC
