### ISSUE TITLE
Use templates body as payload for notifications and subject for other HTML related stuff

### ISSUE THREAD

**Issue by ayashjorden** [bosun-monitor/bosun#1096] opened 2015-06-23 19:57 UTC
Hi all, as described in the docs, I'm using the templates subject as body for POSTing stuff to our hipchat bot. the problem I encounter is in Bosun main view (list of alerts) where the template subject is presented when clicking an alert for details.

![image](https://cloud.githubusercontent.com/assets/4204371/8315624/aae096e2-19fa-11e5-9708-49dbb6dfe8d4.png)

Suggested is to use templates' body as payload for notification (POST notifications mainly). a flag can be also added to let the user which template will use the subject as payload and which will use the body.

Thanks,
Yarden

**Comment by captncraig** [comment] 2015-06-23 20:00
So in notification we could specify 

    post=http://hipchat
    useBody = true

I kinda like it.

**Comment by ayashjorden** [comment] 2015-06-23 20:09
Yup, thats what I thought.
Is it still large refactor as @mjibson said ?

**Comment by captncraig** [comment] 2015-06-23 20:09
no, that alone should be pretty easy. A small addition to conf, and a single check when we send the post. You could probably handle that.

**Comment by ayashjorden** [comment] 2015-06-23 20:12
Were would it be in the code?

**Comment by captncraig** [comment] 2015-06-23 20:29
The posts actually get dispatched around https://github.com/bosun-monitor/bosun/blob/2454db52018ff3d34c84b5f0e9544c77dc96b096/cmd/bosun/conf/notify.go#L31

**Comment by ayashjorden** [comment] 2015-06-24 15:07
Added UseBody boolean, it works.
Now we're left with two things:
1. Action page, 'Send Notification' message payload is also using template body, I'd like to override it so it will use templates' subject anyway (when taking action on multiple alerts, we need to list only the template subject and not the json message in the body).
2. Bosun main page, let the alert list use the template's subject.

Please point me in the direction for solving the above.
Thanks,
Yarden

**Comment by mjibson** [comment] 2015-06-24 18:48
We should also consider changing `.` to instead have `.Body` and `.Subject`. I prefer that method instead of `useBody` because it allows a user to use both if they wish, which is certainly possible.

**Comment by captncraig** [comment] 2015-06-24 18:57
+1 to matt's idea

**Comment by ayashjorden** [comment] 2015-06-24 19:42
+1 to @mjibson suggestion

**Comment by ayashjorden** [comment] 2015-06-25 05:43
@mjibson take a look on this one:
![image](https://cloud.githubusercontent.com/assets/4204371/8347997/0be3cb1e-1b16-11e5-9026-062963848f9a.png)

As you can see, the template's subject is listed in the list of incidents, and I'd like to list the alerts' subject event when UseBody=true, There is no use for the alerts' body when ACK-ing/CLOSE-ing

Any idea?

**Comment by ayashjorden** [comment] 2015-07-26 19:53
Hi, 
Is there any way I can help with @mjibson suggestion?

I think that discussion is needed about the content of the message that gets sent from the action page, grouped/non-grouped...

Thanks,
Yarden

**Comment by ukn** [comment] 2015-09-24 09:33
+1 to get this feature implemented

**Comment by digrich** [comment] 2015-10-29 21:04
+1 

Can't we have all variables (Alert,Group,History etc) accessible to post notification as they are available to templates?

**Comment by captncraig** [comment] 2015-10-29 22:24
I was just thinking how maybe we should allow a notification to have its
own template that will be rendered on demand when the notification is sent,
that would have access to all the same things as a regular template. I
haven't given it too much thought, but that would make a notification able
to be entirely decoupled from the alerts template. It may have a bit
inconsistent data if it is rendered with the current state rather than
rendered at the time the alert went active though. Still thinking it
through a bit.

**Comment by digrich** [comment] 2015-10-29 23:14
That would work very well. In my case, I have to send out notification over email and also to opsgenie, which is having it's own alert message structure. Separate templates will really give the freedom to send out alert data to multiple systems in the format they understand. 

This will really make bosun to integrate seamlessly with other systems.

**Comment by ayashjorden** [comment] 2015-11-23 09:01
Hi all,
Any update on this issue? is it planned for implementation?

**Comment by sysadmin1139** [comment] 2015-12-14 22:55
Allowing either the template variables to be used for the `body` override, or allow a different template entirely for `post` actions, would be great. Right now I have to do something ugly like this in order to integrate with two different API services:

```
notification hipchat_ops {
  post = https://api.hipchat.com/v2/room/ops?auth_token=${env.HC_TOKEN}
  contentType = application/json
}

notification pagerduty {
  post = https://events.pagerduty.com/generic/2010-04-15/create_event.json
  contentType = application/json
}

template hipchat {
  subject = [hipchat specific JSON with lots of {{.Alert.Var}} in it]
}

template pagerduty_ops {
  subject = [pagerduty specific JSON with lots of {{.Alert.Var}} in it]
}

alert everything_is_terrible_hc {
  crit = $terrible > 1
  critNotification = hipchat_ops
  template = hipchat
}

alert everything_is_terrible_pd {
  crit = $terrible > 1
  critNotification = pagerduty
  template = pagerduty_ops
}
```
I need to define the alarm twice because I can't use the same template for both Pagerduty and Hipchat. If I want to emit an email, I'll need a third declaration of the same alert, with the same thresholds, just to get a third template+notification chain going.

And due to how the different services handle authentication (or not) I can have a generic notifier for one but not the other, and a service-specific template for one, but not the other.

---
If the template variables were in scope, I could write the `notification` configs with `body` specific to that particular URL. I could then use the `template` statement to format any email notices I send.

```
notification pagerduty {
  post = https://events.pagerduty.com/generic/2010-04-15/create_event.json
  contentType = application/json
  body = [PagerDuty specific JSON with lots of {{.Alert.Var}} in it]
  next = hipchat_ops
}

notification hipchat_ops {
  post = https://api.hipchat.com/v2/room/ops?auth_token=${env.HC_TOKEN}
  contentType = application/json
  body = [HipChat specific JSON with lots of {{.Alert.Var}} in it]
  next = email_archive
}

notification email_archive {
  email = archive-alerts@example.com
}

template email {
  subject = [things]
  body = [stuff]
}

alert everything_is_terrible {
  crit = $terrible > 1
  critNotification = pagerduty
  template = email
}
```
Much clearer, and without duplication.

The problem is that each PUT, GET, or email requires its own information schema based on the notification method. A unified template for all of those isn't going to work. Providing the template variables in the `body` attribute is one way to fix that.

**Comment by djohnsen** [comment] 2016-03-04 17:06
+1 for having template variables in scope within a notification to customize content by service being notified.

**Comment by sathee005** [comment] 2016-10-07 04:18
+1 it would be great if we can access alert variable inside notification or I can declare a custom description variable  for each alert and use that under notification.  On pager duty incident_key is  used to avoid duplication of alerts for that we can use subject. If we include all variables on subject then when the threshold changes during alert it creates duplicate incidents on pager duty. Any work around for this other than including  alert variables   ?

**Comment by kylebrandt** [comment] 2017-09-05 12:25
Will be fixed in https://github.com/bosun-monitor/bosun/pull/2135

@sathee005 To your question, this can be done already with the V() func http://bosun.org/definitions#vstring-string

**Closed** 2017-09-28 17:12 UTC
Labels: Notifications, Post Notifications Crappy
