### ISSUE TITLE
Lookups and InfluxDB

### ISSUE THREAD

**Issue by nhproject** [bosun-monitor/bosun#1503] opened 2015-12-09 10:38 UTC
Hi,

Is it possible to use lookups when using InfluxDB as my database?
If so, then how should I do it?

I'm getting "0 crits, 0 warns, 0 unevaluated, 0 unknown" when using the lookup.

Nitz

**Comment by kylebrandt** [comment] 2015-12-09 13:07
Considering this a dupe of https://github.com/bosun-monitor/bosun/issues/1035 , needs to be changed not to use search if possible.

**Closed by kylebrandt** 2015-12-09 13:07 UTC
