### ISSUE TITLE
[Feature Request] back to normal notifications (for PagerDuty, etc)

### ISSUE THREAD

**Issue by dimamedvedev** [bosun-monitor/bosun#1731] opened 2016-05-12 14:29 UTC
Back to normal notifications are useful for specific high-priority notifications that make phone beep/ring (e.g PagerDuty, VictorOps, etc). That way intermittent problems (e.g. network hiccups) wont wake on-duty engineers needlessly.

**Comment by kylebrandt** [comment] 2016-05-12 14:31
dupe of https://github.com/bosun-monitor/bosun/issues/333

**Closed by kylebrandt** 2016-05-12 14:31 UTC
