### ISSUE TITLE
[Feature Request] Ability to automatically close acknowledge alerts when they healed

### ISSUE THREAD

**Issue by Civil** [bosun-monitor/bosun#1804] opened 2016-06-28 09:52 UTC
I know that this is a little bit against proposed Bosun's workflow, but I think if there'll be optional way to automatically close alert if it's healed it'll make some people happy.

This is in particular useful in situations when you have really a lot of alerts in Bosun.

**Comment by kylebrandt** [comment] 2016-06-29 14:42
Considering this a dupe of https://github.com/bosun-monitor/bosun/issues/333 , since I sort of assume this would be part of "normal / recovery" emails

**Closed by kylebrandt** 2016-06-29 14:42 UTC
