### ISSUE TITLE
Variable expansion can be misleading, so should auto-add parens

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#639] opened 2015-01-07 08:36 UTC
Consider:

```
$a = $b / $c
$d = $a > 1
```

This actually does `$b / ($c > 1)` due to operator precedence rules, but that's not obvious from the variable replacement.

Proposal: for variables that are valid expressions and binary nodes (i.e., two arguments and an operator), bosun should auto-add parens around them.

**Comment by Dieterbe** [comment] 2015-01-07 14:07
dup of #635? :)

**Comment by kylebrandt** [comment] 2015-01-31 19:52
Dupe of #635

**Closed by kylebrandt** 2015-01-31 19:52 UTC
