### ISSUE TITLE
Adding comments to already acknowledged incidents

### ISSUE THREAD

**Issue by timurb** [bosun-monitor/bosun#1532] opened 2015-12-21 14:43 UTC
Sometimes you acknowledge alert and then need to add some comment to the log.

It would be nice if we could add comments to already acknowledged incidents.

**Comment by captncraig** [comment] 2015-12-21 16:06
We've had this idea before too. Would essentially be an additional action type you could perform. And a little bit of ui on the incidents page.

**Comment by kylebrandt** [comment] 2016-06-26 17:44
closing as dupe of https://github.com/bosun-monitor/bosun/issues/1767 (this one was first, but already referenced the other one in the PR that adds this feature).

**Closed by kylebrandt** 2016-06-26 17:44 UTC
Labels: bosun, enhancement
