### ISSUE TITLE
can bosun support cluster?

### ISSUE THREAD

**Issue by MyZhang0826** [bosun-monitor/bosun#2360] opened 2018-12-25 08:48 UTC
when bosun down, another bosun will replace it

**Comment by MyZhang0826** [comment] 2018-12-25 09:33
why bosun rule need config in conf?, in some db is not ok?so we can use db cluster

**Comment by svagner** [comment] 2019-01-02 08:37
There is exists pull request - https://github.com/bosun-monitor/bosun/pull/2345 But unfortunately it isn't merged yet:(

**Comment by johnewing1** [comment] 2020-02-14 10:49
Duplicate of #2443

**Closed by johnewing1** 2020-02-14 10:49 UTC
