### ISSUE TITLE
"Too many open files"

### ISSUE THREAD

**Issue by ocharles** [bosun-monitor/bosun#605] opened 2014-12-10 11:34 UTC
I just checked our `bosun` server logs and it's full of:

```
Dec 10 11:31:44 monitoring bosun[7824]: 2014/12/10 11:31:44 http: Accept error: accept tcp [::]:8070: too many open files; retrying in 1s
Dec 10 11:31:44 monitoring bosun[7824]: 2014/12/10 11:31:44 http: proxy error: dial tcp 127.0.0.1:4242: too many open files
Dec 10 11:31:44 monitoring bosun[7824]: 2014/12/10 11:31:44 http: proxy error: dial tcp 127.0.0.1:4242: too many open files
Dec 10 11:31:45 monitoring bosun[7824]: 2014/12/10 11:31:45 http: proxy error: dial tcp 127.0.0.1:4242: too many open files
Dec 10 11:31:45 monitoring bosun[7824]: 2014/12/10 11:31:45 http: proxy error: dial tcp 127.0.0.1:4242: too many open files
Dec 10 11:31:45 monitoring bosun[7824]: 2014/12/10 11:31:45 http: proxy error: dial tcp 127.0.0.1:4242: too many open files
Dec 10 11:31:45 monitoring bosun[7824]: 2014/12/10 11:31:45 http: proxy error: dial tcp 127.0.0.1:4242: too many open files
Dec 10 11:31:45 monitoring bosun[7824]: 2014/12/10 11:31:45 http: proxy error: dial tcp 127.0.0.1:4242: too many open files
Dec 10 11:31:45 monitoring bosun[7824]: 2014/12/10 11:31:45 http: proxy error: dial tcp 127.0.0.1:4242: too many open files
Dec 10 11:31:45 monitoring bosun[7824]: 2014/12/10 11:31:45 http: proxy error: dial tcp 127.0.0.1:4242: too many open files
Dec 10 11:31:45 monitoring bosun[7824]: 2014/12/10 11:31:45 http: proxy error: dial tcp 127.0.0.1:4242: too many open files
Dec 10 11:31:45 monitoring bosun[7824]: 2014/12/10 11:31:45 http: proxy error: dial tcp 127.0.0.1:4242: too many open files
Dec 10 11:31:45 monitoring bosun[7824]: 2014/12/10 11:31:45 http: proxy error: dial tcp 127.0.0.1:4242: too many open files
Dec 10 11:31:45 monitoring bosun[7824]: 2014/12/10 11:31:45 http: Accept error: accept tcp [::]:8070: too many open files; retrying in 1s
Dec 10 11:31:45 monitoring bosun[7824]: 2014/12/10 11:31:45 http: proxy error: dial tcp 127.0.0.1:4242: too many open files
Dec 10 11:31:45 monitoring bosun[7824]: 2014/12/10 11:31:45 http: proxy error: dial tcp 127.0.0.1:4242: too many open files
Dec 10 11:31:46 monitoring bosun[7824]: 2014/12/10 11:31:46 http: proxy error: dial tcp 127.0.0.1:4242: too many open files
Dec 10 11:31:46 monitoring bosun[7824]: 2014/12/10 11:31:46 http: proxy error: dial tcp 127.0.0.1:4242: too many open files
Dec 10 11:31:46 monitoring bosun[7824]: 2014/12/10 11:31:46 http: proxy error: dial tcp 127.0.0.1:4242: too many open files
Dec 10 11:31:46 monitoring bosun[7824]: 2014/12/10 11:31:46 http: proxy error: dial tcp 127.0.0.1:4242: too many open files
```

This has rendered `bosun` unresponsive - at least to the HTTP interface. I've since restarted it, but maybe there is something work with here...

**Comment by kylebrandt** [comment] 2015-03-09 16:15
Dupe of #426

**Closed by kylebrandt** 2015-03-09 16:15 UTC
Labels: bosun, bug, critical
