### ISSUE TITLE
influxdb!!!

### ISSUE THREAD

**Issue by wkshare** [bosun-monitor/bosun#823] opened 2015-03-23 10:34 UTC
We wish to add influxdb support, PR submission, what need to pay attention to the local.

**Comment by wkshare** [comment] 2015-03-23 10:34
http://influxdb.com/

**Comment by rickynils** [comment] 2015-03-31 09:50
@wkshare This issue is a duplicate of #618, please close it.

**Closed** 2015-03-31 14:34 UTC

**Comment by wkshare** [comment] 2015-04-02 06:56
@rickynils  thks
